# Generated by Django 3.1 on 2024-06-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deprtment',
            new_name='Department',
        ),
    ]
