# Generated by Django 3.1 on 2024-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240604_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('finance', 'finance'), ('monitoring and evaluation', 'monitoring and evaluation'), ('her', 'hr'), ('clinical', 'clinical')], max_length=200),
        ),
    ]
