# Generated by Django 3.1 on 2024-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240604_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('finance', 'finance'), ('monitoring and evaluation', 'monitoring and evaluation'), ('her', 'HR'), ('clinical', 'clinical')], max_length=200, unique=True),
        ),
    ]
