# Generated by Django 3.1 on 2024-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240604_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('finance', 'Finance'), ('monitoring and evaluation', 'Monitoring And Evaluation'), ('her', 'HR'), ('clinical', 'Clinical'), ('research', 'Research'), ('Informatics', 'Informatics')], max_length=200, unique=True),
        ),
    ]
